class StudentModel {
  String parent_id;
  String student_id;
  String stud_gr_no;
  String stud_first_name;
  String stud_last_name;
  String stud_middle_name;
  String stud_photo;
  String stud_address;
  String stud_address_permenant;
  String stud_contact;
  String stud_parent_contact;
  String stud_nationality;
  String stud_cast;
  String stud_bdate;
  String stud_id_card_no;
  String stud_join_date;
  String stud_leave_date;
  String stud_is_leave;
  String stud_leave_description;
  String stud_vehicle_no;
  String stud_extra;
  String stud_gender;
  String parent_fullname;
  String parent_occupation;
  String parent_phone;
  String parent_email;
  String parent_annual_income;
  String parent_office_address;
  String is_gov_employee;
  String parent_type;
  String parent_gender;
  String parent_photo;

  StudentModel({
    required this.parent_id,
    required this.student_id,
    required this.stud_gr_no,
    required this.stud_first_name,
    required this.stud_last_name,
    required this.stud_middle_name,
    required this.stud_photo,
    required this.stud_address,
    required this.stud_address_permenant,
    required this.stud_contact,
    required this.stud_parent_contact,
    required this.stud_nationality,
    required this.stud_cast,
    required this.stud_bdate,
    required this.stud_id_card_no,
    required this.stud_join_date,
    required this.stud_leave_date,
    required this.stud_is_leave,
    required this.stud_leave_description,
    required this.stud_vehicle_no,
    required this.stud_extra,
    required this.stud_gender,
    required this.parent_fullname,
    required this.parent_occupation,
    required this.parent_phone,
    required this.parent_email,
    required this.parent_annual_income,
    required this.parent_office_address,
    required this.is_gov_employee,
    required this.parent_type,
    required this.parent_gender,
    required this.parent_photo,
  });

  factory StudentModel.fromJson(Map<String, dynamic> json) {
    return StudentModel(
      parent_id: json['parent_id'].toString(),
      student_id: json['student_id'].toString(),
      stud_gr_no: json['stud_gr_no'].toString(),
      stud_first_name: json['stud_first_name'].toString(),
      stud_last_name: json['stud_last_name'].toString(),
      stud_middle_name: json['stud_middle_name'].toString(),
      stud_photo: json['stud_photo'].toString(),
      stud_address: json['stud_address'].toString(),
      stud_address_permenant: json['stud_address_permenant'].toString(),
      stud_contact: json['stud_contact'].toString(),
      stud_parent_contact: json['stud_parent_contact'].toString(),
      stud_nationality: json['stud_nationality'].toString(),
      stud_cast: json['stud_cast'].toString(),
      stud_bdate: json['stud_bdate'].toString(),
      stud_id_card_no: json['stud_id_card_no'].toString(),
      stud_join_date: json['stud_join_date'].toString(),
      stud_leave_date: json['stud_leave_date'].toString(),
      stud_is_leave: json['stud_is_leave'].toString(),
      stud_leave_description: json['stud_leave_description'].toString(),
      stud_vehicle_no: json['stud_vehicle_no'].toString(),
      stud_extra: json['stud_extra'].toString(),
      stud_gender: json['stud_gender'].toString(),
      parent_fullname: json['parent_fullname'].toString(),
      parent_occupation: json['parent_occupation'].toString(),
      parent_phone: json['parent_phone'].toString(),
      parent_email: json['parent_email'].toString(),
      parent_annual_income: json['parent_annual_income'].toString(),
      parent_office_address: json['parent_office_address'].toString(),
      is_gov_employee: json['is_gov_employee'].toString(),
      parent_type: json['parent_type'].toString(),
      parent_gender: json['parent_gender'].toString(),
      parent_photo: json['parent_photo'].toString(),
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'parent_id': parent_id,
      'student_id': student_id,
      'stud_gr_no': stud_gr_no,
      'stud_first_name': stud_first_name,
      'stud_last_name': stud_last_name,
      'stud_middle_name': stud_middle_name,
      'stud_photo': stud_photo,
      'stud_address': stud_address,
      'stud_address_permenant': stud_address_permenant,
      'stud_contact': stud_contact,
      'stud_parent_contact': stud_parent_contact,
      'stud_nationality': stud_nationality,
      'stud_cast': stud_cast,
      'stud_bdate': stud_bdate,
      'stud_id_card_no': stud_id_card_no,
      'stud_join_date': stud_join_date,
      'stud_leave_date': stud_leave_date,
      'stud_is_leave': stud_is_leave,
      'stud_leave_description': stud_leave_description,
      'stud_vehicle_no': stud_vehicle_no,
      'stud_extra': stud_extra,
      'stud_gender': stud_gender,
      'parent_fullname': parent_fullname,
      'parent_occupation': parent_occupation,
      'parent_phone': parent_phone,
      'parent_email': parent_email,
      'parent_annual_income': parent_annual_income,
      'parent_office_address': parent_office_address,
      'is_gov_employee': is_gov_employee,
      'parent_type': parent_type,
      'parent_gender': parent_gender,
      'parent_photo': parent_photo,
    };
  }
}
